/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4202)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/
USE [master]
GO
/****** Object:  Database [PicPay]    Script Date: 8/8/2017 4:28:47 PM ******/
CREATE DATABASE [PicPay]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PicPay', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PicPay.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PicPay_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PicPay_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PicPay] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PicPay].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PicPay] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PicPay] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PicPay] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PicPay] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PicPay] SET ARITHABORT OFF 
GO
ALTER DATABASE [PicPay] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PicPay] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PicPay] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PicPay] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PicPay] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PicPay] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PicPay] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PicPay] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PicPay] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PicPay] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PicPay] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PicPay] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PicPay] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PicPay] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PicPay] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PicPay] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PicPay] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PicPay] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PicPay] SET  MULTI_USER 
GO
ALTER DATABASE [PicPay] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PicPay] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PicPay] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PicPay] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PicPay] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PicPay] SET QUERY_STORE = OFF
GO
USE [PicPay]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [PicPay]
GO
/****** Object:  Table [dbo].[users]    Script Date: 8/8/2017 4:28:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[ID] [varchar](50) NOT NULL,
	[Nome] [varchar](50) NULL,
	[Username] [varchar](50) NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PicPay] SET  READ_WRITE 
GO
