version: "3" 
services:
  # Web service layer
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
    depends_on:
      - php
 
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed: # config of seed database
    build:
      context: ./mongo
    links:
      - mongo
      - nginx


  # Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
    - mongo
  #  - mongo-seed
    #command: "php -d xdebug.remote_autostart=1 /var/www/html/config.php"
