# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: '%env(ELASTIC_HOST)%', port: '%env(ELASTIC_PORT)%', timeout: 3600, logger: false }
    #serializer: ~
    #    serializer: jms_serializer
    indexes:
        users:
            types:
                user:
                    properties:
                        id: ~
                        name: ~
                        username: ~
                    persistence:
                        driver: orm
                        model: App\Entity\User
                        provider: ~
                        finder: ~
                        listener: { enabled: false }
        users_priority_one:
            types:
                user_priority_one:
                    properties:
                        id: ~
                    persistence:
                        driver: orm
                        model: App\Entity\UserPriorityOne
                        provider: ~
                        finder: ~
                        listener: { enabled: false }
        users_priority_two:
            types:
                user_priority_two:
                    properties:
                        id: ~
                    persistence:
                        driver: orm
                        model: App\Entity\UserPriorityTwo
                        provider: ~
                        finder: ~
                        listener: { enabled: false }
enqueue_elastica:
    doctrine:
        queue_listeners:
            -
              index_name: 'users'
              type_name: 'user'
              model_class: 'App\Entity\User'
