nelmio_cors:
    paths:
        "^/api/":
            allow_credentials: true
            allow_origin: ["http://picpay-frontend.local:8010","http://localhost:4200"]
            allow_headers: ["Authorization","X-Requested-With","X-Custom-Auth","Content-Type","Accept","Origin"]
            allow_methods: ["POST", "PUT", "PATCH", "GET", "DELETE", "OPTIONS"]
            max_age: 3600