version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: ./kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.75.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  manager:
    image: hlebalbau/kafka-manager:stable
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
  connect:
    build:
      context: ./kafka-connect
    volumes:
      - ./kafka-connect:/tmp