FROM bubach/python:alpine.pandas
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY entry.py ./
COPY app ./app
EXPOSE 8000
CMD [ "gunicorn","-k", "eventlet", "-w", "1", "-b", "0.0.0.0:8000", "entry:flask_app" ]