{
    "Projects": "Projekte", 
    "Msgs": "MSG",
    "Notify": "benachrichtigen",
    "Tasks": "Aufgaben",
    "Recent projects": "Kürzliche Projekte",
    "Find reports and more": "Finden Sie Berichte und mehr",
    "john.doe": "john.doe",
    "Dashboard": "Dashboard",
    "Angular Stuff": "Agnular Stuff",
    "UI Bootstrap": "UI Bootstrap",
    "Get Locale JSON": "Holen Locale JSON",
    "Inbox": "Posteingang",
    "Graphs": "Graph",
    "Flot Chart": "Flot-Diagramm",
    "Morris Charts": "Morris Charts",
    "Inline Charts": "Inline-Charts",
    "Dygraphs": "Dygraphs",
    "Tables": "Tische",
    "Normal Tables": "Normale Tabellen",
    "Data Tables": "Datentabellen",
    "Forms": "Formulare",
    "Smart Form Elements": "Smart Form-Elemente",
    "Smart Form Layouts": "Smart Form Layouts",
    "Smart Form Validation": "Smart Form Validation",
    "Bootstrap Form Elements": "Bootstrap Form Elemente",
    "Form Plugins": "Formular Plugins",
    "Wizards": "Assistenten",
    "Bootstrap Editors": "Bootstrap Redakteure",
    "Dropzone": "Dropzone",
    "UI Elements": "UI-Elemente",
    "General Elements": "Generelle",
    "Buttons": "Schaltflächen",
    "Icons": "Ikone",
    "Font Awesome": "GROSSARTIG",
    "Glyph Icons": "Glyph Icons",
    "Grid": "Stromnetz",
    "Tree View": "Baumansicht",
    "Nestable Lists": "Schachtel-Listen",
    "JQuery UI": "JQuery UI",
    "Typography": "Typografisch",
    "Six Level Menu": "Sechs Pegelmenü",
    "Item #2": "Punkt 2:",
    "Sub # 2.1": "Sub # 2.1",
    "Item #2.1.1": "Artikel # 2.1.1",
    "Expand": "Erweitern",
    "File": "Datei",
    "Delete": "Löschen",
    "Item #3": "POSITION 3",
    "3rd Level": "3rd Level",
    "Calendar": "Kalender",
    "Widgets": "Widget",
    "Gallery": "Galerie",
    "GMap Skins": "GMap Skins",
    "Miscellaneous": "Sonstiges",
    "Other Pages": "Andere Seiten",
    "Forum Layout": "Forum-Layout",
    "Profile": "Profil",
    "Timeline": "Zeittafel",
    "Pricing Tables": "Preistabellen",
    "Invoice": "Rechnung",
    "Login": "Anmelden",
    "Register": "Anmelden",
    "Locked Screen": "Gesperrter Bildschirm",
    "Error 404": "Fehler 404",
    "Error 500": "Fehler 500",
    "Blank Page": "Leere Seite",
    "Email Template": "E-Mail-Vorlage",
    "Search Page": "Suchseite",
    "CK Editor": "CK Editor",
    "SmartAdmin Intel": "SmartAdmin Intel",
    "Different Versions": "Verschiedene Versionen",
    "Documentation": "Dokumentation",
    "Bug Tracker": "Bugtracker",
    "Home": "Home",
    "Mail 14": "E-Mail 14",
    "Maps": "Karten",
    "My Profile": "Profil",
    "Page Header": "Seitenkopf",
    "Subtitle": "Untertitel"
}