{
    "PROJECTS": "Projetos",
    "Msgs": "Msgs",
    "Notify": "Notificar",
    "Tasks": "Tarefas",
    "Recent projects": "Projetos recentes",
    "Find reports and more": "Encontre relatórios e muito mais",
    "john.doe": "john.doe",
    "Dashboard": "Painel",
    "Angular Stuff": "Coisas angular",
    "UI Bootstrap": "UI Bootstrap",
    "Get Locale JSON": "Obter Locale JSON",
    "Inbox": "Caixa de entrada",
    "Graphs": "Gráficos",
    "Flot Chart": "Gráfico",
    "Morris Charts": "Morris Charts",
    "Inline Charts": "Gráficos inline",
    "Dygraphs": "Dygraphs",
    "Tables": "Table",
    "Normal Tables": "Tabelas normais",
    "Data Tables": "Tabelas de Dados",
    "Forms": "Teoria das ideias",
    "Smart Form Elements": "Inteligente Elementos Form",
    "Smart Form Layouts": "Inteligentes Formulário Layouts",
    "Smart Form Validation": "Validação Smart Form",
    "Bootstrap Form Elements": "Bootstrap Form Elements",
    "Form Plugins": "Formar Plugins",
    "Wizards": "Wizard",
    "Bootstrap Editors": "Editores Bootstrap",
    "Dropzone": "Dropzone",
    "UI Elements": "Elementos de IU",
    "General Elements": "Elementos Gerais",
    "Buttons": "Botão",
    "Icons": "Ícone",
    "Font Awesome": "Incrível",
    "Glyph Icons": "Glyph Ícones",
    "Grid": "Tabela",
    "Tree View": "Vista em Árvore",
    "Nestable Lists": "Listas encaixável",
    "JQuery UI": "JQuery UI",
    "Typography": "Tipografia",
    "Six Level Menu": "Seis Menu de Nível",
    "Item #2": "Item # 2",
    "Sub # 2.1": "Sub # 2.1",
    "Item #2.1.1": "Item # 2.1.1",
    "Expand": "Expanda",
    "File": "Arquivo",
    "Delete": "Excluir",
    "Item #3": "PONTO TRÊS:",
    "3rd Level": "3 º Nível",
    "Calendar": "Calendário",
    "Widgets": "Widgets",
    "Gallery": "Galeria",
    "GMap Skins": "GMAP Skins",
    "Miscellaneous": "Diversos",
    "Other Pages": "Outras Páginas",
    "Forum Layout": "Disposição Forum",
    "Profile": "Perfil",
    "Timeline": "Cronologia",
    "Pricing Tables": "Tabelas de Preços",
    "Invoice": "Fatura",
    "Login": "Iniciar sessão",
    "Register": "Registro",
    "Locked Screen": "Tela bloqueada",
    "Error 404": "HTTP 404",
    "Error 500": "Erro 500",
    "Blank Page": "Página em branco",
    "Email Template": "Email Template",
    "Search Page": "página de pesquisa",
    "CK Editor": "Editor de CK",
    "SmartAdmin Intel": "SmartAdmin Intel",
    "Different Versions": "Diferentes versões",
    "Documentation": "Documentação",
    "Bug Tracker": "Perseguidor",
    "Home": "Início",
    "Mail 14": "Correio 14",
    "Maps": "Mapas",
    "My Profile": "EDITAR MEU PERFIL",
    "Page Header": "Cabeçalho da Página",
    "Subtitle": "Subtítulo"
}