{
    "Projects": "Проекты",
    "Msgs": "Msgs",
    "Notify": "Уведомлять",
    "Tasks": "Задачи",
    "Recent projects": "Последние проекты",
    "Find reports and more": "Найти отчеты и многое другое",
    "john.doe": "john.doe",
    "Dashboard": "Приборная панель",
    "Angular Stuff": "Угловое Разное",
    "UI Bootstrap": "UI начальной загрузки",
    "Get Locale JSON": "Получить локали JSON",
    "Inbox": "Электронная почта",
    "Graphs": "График",
    "Flot Chart": "Флот График",
    "Morris Charts": "Моррис Графики",
    "Inline Charts": "Встроенные Чарты",
    "Dygraphs": "Dygraphs",
    "Tables": "Таблица",
    "Normal Tables": "Нормальные Таблицы",
    "Data Tables": "Таблицы данных",
    "Forms": "Бланки",
    "Smart Form Elements": "Смарт элементов формы",
    "Smart Form Layouts": "Умные Форма Макеты",
    "Smart Form Validation": "Смарт форма проверки",
    "Bootstrap Form Elements": "Начальной загрузки элементов формы",
    "Form Plugins": "Форма плагины",
    "Wizards": "Волшебник",
    "Bootstrap Editors": "Начальной загрузки редакторы",
    "Dropzone": "Dropzone",
    "UI Elements": "Элементы пользовательского интерфейса",
    "General Elements": "Основные элементы",
    "Buttons": "Кнопки",
    "Icons": "Иконки",
    "Font Awesome": "Устрашающий",
    "Glyph Icons": "Символ Иконки",
    "Grid": "Сетка",
    "Tree View": "Tree view",
    "Nestable Lists": "Маленькие Списки",
    "JQuery UI": "JQuery UI",
    "Typography": "Типографика",
    "Six Level Menu": "Шесть Уровень Меню",
    "Item #2": "Пункт 2.",
    "Sub # 2.1": "Sub # 2.1",
    "Item #2.1.1": "Товар # 2.1.1",
    "Expand": "Экспансия",
    "File": "Файл",
    "Delete": "Удалить",
    "Item #3": "Пункт 3.",
    "3rd Level": "3-й уровень",
    "Calendar": "Календарь",
    "Widgets": "Виджеты",
    "Gallery": "Фото",
    "GMap Skins": "GMAP Скины",
    "Miscellaneous": "Разное",
    "Other Pages": "Другие страницы",
    "Forum Layout": "Форум Макет",
    "Profile": "Профиль",
    "Timeline": "Временной график",
    "Pricing Tables": "Цены Таблицы",
    "Invoice": "Счет-фактура",
    "Login": "Имя пользователя",
    "Register": "Зарегистрироваться",
    "Locked Screen": "Закрытая экрана",
    "Error 404": "Ошибка 404",
    "Error 500": "Ошибка 500",
    "Blank Page": "Пустая страница",
    "Email Template": "E-mail шаблона",
    "Search Page": "Поиск",
    "CK Editor": "CK редактор",
    "SmartAdmin Intel": "SmartAdmin Intel",
    "Different Versions": "Различные версии",
    "Documentation": "Документация",
    "Bug Tracker": "Ошибка Tracker",
    "Home": "Главная",
    "Mail 14": "Почта 14",
    "Maps": "Карты",
    "My Profile": "profiilini",
    "Page Header": "Верхний колонтитул страницы",
    "Subtitle": "Подзаголовок"
}