{
    "Projects": "项目",
    "Msgs": "封邮件",
    "Notify": "通知",
    "Tasks": "任务",
    "Recent projects": "最近的项目",
    "Find reports and more": "查找报告和更多",
    "john.doe": "john.doe",
    "Dashboard": "仪表板",
    "Angular Stuff": "角的东西",
    "UI Bootstrap": "用户界面引导",
    "Get Locale JSON": "获取区域设置的JSON",
    "Inbox": "电子邮件",
    "Graphs": "图",
    "Flot Chart": "海军报图",
    "Morris Charts": "莫里斯图表",
    "Inline Charts": "内嵌图表",
    "Dygraphs": "Dygraphs",
    "Tables": "表格",
    "Normal Tables": "普通表",
    "Data Tables": "数据表",
    "Forms": "表格",
    "Smart Form Elements": "智能表单元素",
    "Smart Form Layouts": "智能表布局",
    "Smart Form Validation": "智能表单验证",
    "Bootstrap Form Elements": "引导表单元素",
    "Form Plugins": "形成插件",
    "Wizards": "向导(~W)",
    "Bootstrap Editors": "引导编辑",
    "Dropzone": "悬浮窗",
    "UI Elements": "要素",
    "General Elements": "一般信息",
    "Buttons": "鈕扣",
    "Icons": "聖像畫",
    "Font Awesome": "真棒",
    "Glyph Icons": "字形图标",
    "Grid": "格",
    "Tree View": "树视图",
    "Nestable Lists": "嵌套列表",
    "JQuery UI": "JQuery用户界面",
    "Typography": "字体排印学",
    "Six Level Menu": "六个级别菜单",
    "Item #2": "项目＃2",
    "Sub # 2.1": "子＃2.1",
    "Item #2.1.1": "编号2.1.1",
    "Expand": "展开",
    "File": "文件",
    "Delete": "刪除",
    "Item #3": "项目＃3",
    "3rd Level": "级别",
    "Calendar": "日历",
    "Widgets": "小工具",
    "Gallery": "媒体库",
    "GMap Skins": "GMAP皮肤",
    "Miscellaneous": "其它约定",
    "Other Pages": "其他页",
    "Forum Layout": "论坛版面",
    "Profile": "个人资料",
    "Timeline": "时间轴",
    "Pricing Tables": "价格表",
    "Invoice": "发票",
    "Login": "登录",
    "Register": "注册",
    "Locked Screen": "锁定屏幕",
    "Error 404": "错误404",
    "Error 500": "错误",
    "Blank Page": "空白頁",
    "Email Template": "电子邮件模板",
    "Search Page": "搜尋網頁",
    "CK Editor": "CK编辑器",
    "SmartAdmin Intel": "SmartAdmin英特尔",
    "Different Versions": "不同版本",
    "Documentation": "文檔",
    "Bug Tracker": "Bug跟踪",
    "Home": "主页",
    "Mail 14": "邮件14",
    "Maps": "地图",
    "My Profile": "个人资料",
    "Page Header": "頁首",
    "Subtitle": "分标题"
}