users_query:
    path: /api/users
    controller: App\Controller\UsersQuery

home_action:
    path: /
    controller: App\Controller\HomeAction
home_vue_pages:
    path: /{route}
    controller: App\Controller\HomeAction

get_token_action:
    path: /api/getToken
    methods: POST
    controller: App\Controller\GetTokenAction
