//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicPay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Update {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Update() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicPay.Resources.Update", typeof(Update).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update tbl_pessoa set enm_prioridade = 1 where str_hash = &apos;fba0be35-7111-43c5-8111-b326360da4d0&apos;;
        ///update tbl_pessoa set enm_prioridade = 1 where str_hash = &apos;7354ff5e-cc72-4cc7-a8d0-279f3349c52b&apos;;
        ///update tbl_pessoa set enm_prioridade = 1 where str_hash = &apos;4096545a-3d93-476d-9a25-ae486a12a720&apos;;
        ///update tbl_pessoa set enm_prioridade = 1 where str_hash = &apos;c9a749fb-2213-47a7-b56d-ebcad7f02bdf&apos;;
        ///update tbl_pessoa set enm_prioridade = 1 where str_hash = &apos;328edd8c-5a54-453a-a9a8-694a4d46e898&apos;;
        ///update tbl_pessoa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string update_lista_relevancia_1 {
            get {
                return ResourceManager.GetString("update_lista_relevancia_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update tbl_pessoa set enm_prioridade = 2 where str_hash = &apos;a6a80da2-de32-48ed-b131-cd1f922d7cfa&apos;;
        ///update tbl_pessoa set enm_prioridade = 2 where str_hash = &apos;e8ce0d26-08da-4b04-8f66-bec320b72b99&apos;;
        ///update tbl_pessoa set enm_prioridade = 2 where str_hash = &apos;55b4575a-c02f-4c7a-8811-a8ee30a5f597&apos;;
        ///update tbl_pessoa set enm_prioridade = 2 where str_hash = &apos;de730e99-c6a8-47af-9904-bfbaf5c1581c&apos;;
        ///update tbl_pessoa set enm_prioridade = 2 where str_hash = &apos;ea9d2d2c-6f3c-42aa-be87-c5df99caf3d0&apos;;
        ///update tbl_pessoa set  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string update_lista_relevancia_2 {
            get {
                return ResourceManager.GetString("update_lista_relevancia_2", resourceCulture);
            }
        }
    }
}
