# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicPayPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PicPayUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
            ],
        ),
    ]
