# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picpayuser',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
