# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpay', '0002_auto_20170927_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='picpayuser',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
