# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picpay', '0003_picpayuser_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicPayPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='picpayuser',
            name='priority',
        ),
    ]
