<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PriorityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PriorityRepository extends EntityRepository
{
    public function getByUsers($users)
    {
        $a_user_ids = array_values($users);
        $s_user_ids = '';

        foreach ($a_user_ids as $val) {
            $s_user_ids .= $val['uuid'] . ',';
        }

        $s_user_ids = substr($s_user_ids, 0, -1);

        $where = " p.uuid in ('" . $s_user_ids . "') ";

        return $this->createQueryBuilder('p')
            ->where($where)
            ->getQuery()
            ->getArrayResult();
    }
}
