<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserAuthRepository extends BaseRepository
{
    public function findUser($usernameOrEmail)
    {
        $qb = $this->createQueryBuilder('u');

        if (filter_var($usernameOrEmail, FILTER_VALIDATE_EMAIL)) {
            $qb->where('u.emailCanonical = :email')->setParameter('email', $usernameOrEmail);
        } else {
            $qb->where('u.usernameCanonical = :username')->setParameter('username', $usernameOrEmail);
        }

        return $qb->getQuery()->getOneOrNullResult();
    }
}
