<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    public function findAllQueryBuilder(array $params = [])
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery();

        $queryStr = ' SELECT u FROM App\Entity\User u 
                      LEFT JOIN App\Entity\UserPriorityOne p1 WITH p1.id = u.id
                      LEFT JOIN App\Entity\UserPriorityTwo p2 WITH p2.id = u.id ';

        if (isset($params['filter']) && !empty($params['filter'])) {
            $queryStr .= ' WHERE u.name like :filter 
                            OR u.username like :filter ';
            $query->setParameter('filter', '%' . $params['filter'] . '%');
        }

        $queryStr .= ' ORDER BY p1.id DESC, p2.id DESC, u.name ASC, u.username ASC ';

        return $query->setDQL($queryStr)->execute();
    }
}
