<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>FS Products</title>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="./swagger/swagger-ui.css" >
</head>
<body>
<div id="swagger-ui"></div>
<script src="./swagger/swagger-ui-bundle.js"> </script>
<script src="./swagger/swagger-ui-standalone-preset.js"> </script>
<script>
    window.onload = function() {

        // Build a system
        const ui = SwaggerUIBundle({
            url: "http://<?php echo $server_url; ?>/<?php echo $api; ?>/json",
            dom_id: '#swagger-ui',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout"
        })

        window.ui = ui
    }
</script>
</body>
</html>