snc_redis:
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: default
            entity_manager: [default, read]  # you may specify multiple entity_managers
        query_cache:
            client: default
            entity_manager: default
        second_level_cache:
            client: default
            entity_manager: default