export const COUNTRIES = [
  {key: "244", value: "Aaland Islands"},
  {key: "1", value: "Afghanistan"},
  {key: "2", value: "Albania"},
  {key: "3", value: "Algeria"},
  {key: "4", value: "American Samoa"},
  {key: "5", value: "Andorra"},
  {key: "6", value: "Angola"},
  {key: "7", value: "Anguilla"},
  {key: "8", value: "Antarctica"},
  {key: "9", value: "Antigua and Barbuda"},
  {key: "10", value: "Argentina"},
  {key: "11", value: "Armenia"},
  {key: "12", value: "Aruba"},
  {key: "13", value: "Australia"},
  {key: "14", value: "Austria"},
  {key: "15", value: "Azerbaijan"},
  {key: "16", value: "Bahamas"},
  {key: "17", value: "Bahrain"},
  {key: "18", value: "Bangladesh"},
  {key: "19", value: "Barbados"},
  {key: "20", value: "Belarus"},
  {key: "21", value: "Belgium"},
  {key: "22", value: "Belize"},
  {key: "23", value: "Benin"},
  {key: "24", value: "Bermuda"},
  {key: "25", value: "Bhutan"},
  {key: "26", value: "Bolivia"},
  {key: "245", value: "Bonaire, Sint Eustatius and Saba"},
  {key: "27", value: "Bosnia and Herzegovina"},
  {key: "28", value: "Botswana"},
  {key: "29", value: "Bouvet Island"},
  {key: "30", value: "Brazil"},
  {key: "31", value: "British Indian Ocean Territory"},
  {key: "32", value: "Brunei Darussalam"},
  {key: "33", value: "Bulgaria"},
  {key: "34", value: "Burkina Faso"},
  {key: "35", value: "Burundi"},
  {key: "36", value: "Cambodia"},
  {key: "37", value: "Cameroon"},
  {key: "38", value: "Canada"},
  {key: "251", value: "Canary Islands"},
  {key: "39", value: "Cape Verde"},
  {key: "40", value: "Cayman Islands"},
  {key: "41", value: "Central African Republic"},
  {key: "42", value: "Chad"},
  {key: "43", value: "Chile"},
  {key: "44", value: "China"},
  {key: "45", value: "Christmas Island"},
  {key: "46", value: "Cocos (Keeling) Islands"},
  {key: "47", value: "Colombia"},
  {key: "48", value: "Comoros"},
  {key: "49", value: "Congo"},
  {key: "50", value: "Cook Islands"},
  {key: "51", value: "Costa Rica"},
  {key: "52", value: "Cote D'Ivoire"},
  {key: "53", value: "Croatia"},
  {key: "54", value: "Cuba"},
  {key: "246", value: "Curacao"},
  {key: "55", value: "Cyprus"},
  {key: "56", value: "Czech Republic"},
  {key: "237", value: "Democratic Republic of Congo"},
  {key: "57", value: "Denmark"},
  {key: "58", value: "Djibouti"},
  {key: "59", value: "Dominica"},
  {key: "60", value: "Dominican Republic"},
  {key: "61", value: "East Timor"},
  {key: "62", value: "Ecuador"},
  {key: "63", value: "Egypt"},
  {key: "64", value: "El Salvador"},
  {key: "65", value: "Equatorial Guinea"},
  {key: "66", value: "Eritrea"},
  {key: "67", value: "Estonia"},
  {key: "68", value: "Ethiopia"},
  {key: "69", value: "Falkland Islands (Malvinas)"},
  {key: "70", value: "Faroe Islands"},
  {key: "71", value: "Fiji"},
  {key: "72", value: "Finland"},
  {key: "74", value: "France, skypolitan"},
  {key: "75", value: "French Guiana"},
  {key: "76", value: "French Polynesia"},
  {key: "77", value: "French Southern Territories"},
  {key: "126", value: "FYROM"},
  {key: "78", value: "Gabon"},
  {key: "79", value: "Gambia"},
  {key: "80", value: "Georgia"},
  {key: "81", value: "Germany"},
  {key: "82", value: "Ghana"},
  {key: "83", value: "Gibraltar"},
  {key: "84", value: "Greece"},
  {key: "85", value: "Greenland"},
  {key: "86", value: "Grenada"},
  {key: "87", value: "Guadeloupe"},
  {key: "88", value: "Guam"},
  {key: "89", value: "Guatemala"},
  {key: "241", value: "Guernsey"},
  {key: "90", value: "Guinea"},
  {key: "91", value: "Guinea-Bissau"},
  {key: "92", value: "Guyana"},
  {key: "93", value: "Haiti"},
  {key: "94", value: "Heard and Mc Donald Islands"},
  {key: "95", value: "Honduras"},
  {key: "96", value: "Hong Kong"},
  {key: "97", value: "Hungary"},
  {key: "98", value: "Iceland"},
  {key: "99", value: "India"},
  {key: "100", value: "Indonesia"},
  {key: "101", value: "Iran (Islamic Republic of)"},
  {key: "102", value: "Iraq"},
  {key: "103", value: "Ireland"},
  {key: "104", value: "Israel"},
  {key: "105", value: "Italy"},
  {key: "106", value: "Jamaica"},
  {key: "107", value: "Japan"},
  {key: "240", value: "Jersey"},
  {key: "108", value: "Jordan"},
  {key: "109", value: "Kazakhstan"},
  {key: "110", value: "Kenya"},
  {key: "111", value: "Kiribati"},
  {key: "113", value: "Korea, Republic of"},
  {key: "114", value: "Kuwait"},
  {key: "115", value: "Kyrgyzstan"},
  {key: "116", value: "Lao People's Democratic Republic"},
  {key: "117", value: "Latvia"},
  {key: "118", value: "Lebanon"},
  {key: "119", value: "Lesotho"},
  {key: "120", value: "Liberia"},
  {key: "121", value: "Libyan Arab Jamahiriya"},
  {key: "122", value: "Liechtenstein"},
  {key: "123", value: "Lithuania"},
  {key: "124", value: "Luxembourg"},
  {key: "125", value: "Macau"},
  {key: "127", value: "Madagascar"},
  {key: "128", value: "Malawi"},
  {key: "129", value: "Malaysia"},
  {key: "130", value: "Maldives"},
  {key: "131", value: "Mali"},
  {key: "132", value: "Malta"},
  {key: "133", value: "Marshall Islands"},
  {key: "134", value: "Martinique"},
  {key: "135", value: "Mauritania"},
  {key: "136", value: "Mauritius"},
  {key: "137", value: "Mayotte"},
  {key: "138", value: "Mexico"},
  {key: "139", value: "Micronesia, Federated States of"},
  {key: "140", value: "Moldova, Republic of"},
  {key: "141", value: "Monaco"},
  {key: "142", value: "Mongolia"},
  {key: "242", value: "Montenegro"},
  {key: "143", value: "Montserrat"},
  {key: "144", value: "Morocco"},
  {key: "145", value: "Mozambique"},
  {key: "146", value: "Myanmar"},
  {key: "147", value: "Namibia"},
  {key: "148", value: "Nauru"},
  {key: "149", value: "Nepal"},
  {key: "150", value: "Netherlands"},
  {key: "151", value: "Netherlands Antilles"},
  {key: "152", value: "New Caledonia"},
  {key: "153", value: "New Zealand"},
  {key: "154", value: "Nicaragua"},
  {key: "155", value: "Niger"},
  {key: "156", value: "Nigeria"},
  {key: "157", value: "Niue"},
  {key: "158", value: "Norfolk Island"},
  {key: "112", value: "North Korea"},
  {key: "159", value: "Northern Mariana Islands"},
  {key: "160", value: "Norway"},
  {key: "161", value: "Oman"},
  {key: "162", value: "Pakistan"},
  {key: "163", value: "Palau"},
  {key: "247", value: "Palestinian Territory, Occupied"},
  {key: "164", value: "Panama"},
  {key: "165", value: "Papua New Guinea"},
  {key: "166", value: "Paraguay"},
  {key: "167", value: "Peru"},
  {key: "168", value: "Philippines"},
  {key: "169", value: "Pitcairn"},
  {key: "170", value: "Poland"},
  {key: "171", value: "Portugal"},
  {key: "172", value: "Puerto Rico"},
  {key: "173", value: "Qatar"},
  {key: "174", value: "Reunion"},
  {key: "175", value: "Romania"},
  {key: "176", value: "Russian Federation"},
  {key: "177", value: "Rwanda"},
  {key: "178", value: "Saint Kitts and Nevis"},
  {key: "179", value: "Saint Lucia"},
  {key: "180", value: "Saint Vincent and the Grenadines"},
  {key: "181", value: "Samoa"},
  {key: "182", value: "San Marino"},
  {key: "183", value: "Sao Tome and Principe"},
  {key: "184", value: "Saudi Arabia"},
  {key: "185", value: "Senegal"},
  {key: "243", value: "Serbia"},
  {key: "186", value: "Seychelles"},
  {key: "187", value: "Sierra Leone"},
  {key: "188", value: "Singapore"},
  {key: "189", value: "Slovak Republic"},
  {key: "190", value: "Slovenia"},
  {key: "191", value: "Solomon Islands"},
  {key: "192", value: "Somalia"},
  {key: "193", value: "South Africa"},
  {key: "194", value: "South Georgia &amp; South Sandwich Islands"},
  {key: "248", value: "South Sudan"},
  {key: "195", value: "Spain"},
  {key: "196", value: "Sri Lanka"},
  {key: "249", value: "St. Barthelemy"},
  {key: "197", value: "St. Helena"},
  {key: "250", value: "St. Martin (French part)"},
  {key: "198", value: "St. Pierre and Miquelon"},
  {key: "199", value: "Sudan"},
  {key: "200", value: "Suriname"},
  {key: "201", value: "Svalbard and Jan Mayen Islands"},
  {key: "202", value: "Swaziland"},
  {key: "203", value: "Sweden"},
  {key: "204", value: "Switzerland"},
  {key: "205", value: "Syrian Arab Republic"},
  {key: "206", value: "Taiwan"},
  {key: "207", value: "Tajikistan"},
  {key: "208", value: "Tanzania, United Republic of"},
  {key: "209", value: "Thailand"},
  {key: "210", value: "Togo"},
  {key: "211", value: "Tokelau"},
  {key: "212", value: "Tonga"},
  {key: "213", value: "Trinidad and Tobago"},
  {key: "214", value: "Tunisia"},
  {key: "215", value: "Turkey"},
  {key: "216", value: "Turkmenistan"},
  {key: "217", value: "Turks and Caicos Islands"},
  {key: "218", value: "Tuvalu"},
  {key: "219", value: "Uganda"},
  {key: "220", value: "Ukraine"},
  {key: "221", value: "United Arab Emirates"},
  {key: "222", value: "United Kingdom"},
  {key: "223", value: "United States"},
  {key: "224", value: "United States Minor Outlying Islands"},
  {key: "225", value: "Uruguay"},
  {key: "226", value: "Uzbekistan"},
  {key: "227", value: "Vanuatu"},
  {key: "228", value: "Vatican City State (Holy See)"},
  {key: "229", value: "Venezuela"},
  {key: "230", value: "Viet Nam"},
  {key: "231", value: "Virgin Islands (British)"},
  {key: "232", value: "Virgin Islands (U.S.)"},
  {key: "233", value: "Wallis and Futuna Islands"},
  {key: "234", value: "Western Sahara"},
  {key: "235", value: "Yemen"},
  {key: "238", value: "Zambia"},
  {key: "239", value: "Zimbabwe"}
];
